import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreatingConducts1960616524265 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            INSERT INTO conduta (id_conduct, orelha_esquerda, orelha_direita, irda, tipo_teste, descricao_resultado, descricao_acompanhamento, fk_fonoaudiologo) VALUES
                (5, 1, 1, 0, 2, 'Na presente data apresentou respostas presentes/satisfatórias no reteste “da orelhinha” (TAN), bilateralmente, sem presença de indicadores de risco para deficiência auditiva (IRDA).', 'Foi realizada orientação verbal e entregue orientação escrita sobre as etapas do desenvolvimento auditivo e de linguagem', NULL),
                (6, 1, 1, 1, 2, 'Na presente data apresentou respostas presentes/satisfatórias no reteste “da orelhinha” (TAN), bilateralmente, com presença de indicadores de risco para deficiência auditiva (IRDA).', 'Como apresenta IRDA, necessita realizar PEATE-A no primeiro mês de vida e acompanhar o desenvolvimento auditivo nas consultas até os dois anos de idade. Por recomendações do Ministério da Saúde (2012), deverá realizar avaliação audiológica comportamental (VRA e limitância acústica) entre sete e 12 meses de idade. Foi realizada orientação verbal e entregue orientação escrita sobre as etapas do desenvolvimento auditivo e de linguagem', NULL),
                (7, 0, 0, 0, 2, 'Na presente data apresentou respostas ausentes/insatisfatórias no reteste “da orelhinha” (TAN) bilateralmente, sem presença de indicadores de risco para deficiência auditiva (IRDA).', 'Foi realizada orientação verbal e entregue orientação escrita sobre a necessidade de avaliação para diagnóstico audiológico diferencial o mais breve possível, incluindo pesquisa de PEATE/BERA e, se necessário, intervenção especializada', NULL),
                (8, 1, 0, 0, 2, 'Na presente data apresentou respostas ausentes/insatisfatórias no reteste “da orelhinha” (TAN) à direita, sem presença de indicadores de risco para deficiência auditiva (IRDA).', 'Foi realizada orientação verbal e entregue orientação escrita sobre a necessidade de avaliação para diagnóstico audiológico diferencial o mais breve possível, incluindo pesquisa de PEATE/BERA e, se necessário, intervenção especializada', NULL),
                (9, 0, 1, 0, 2, 'Na presente data apresentou respostas ausentes/insatisfatórias no reteste “da orelhinha” (TAN) à esquerda, sem presença de indicadores de risco para deficiência auditiva (IRDA).', 'Foi realizada orientação verbal e entregue orientação escrita sobre a necessidade de avaliação para diagnóstico audiológico diferencial o mais breve possível, incluindo pesquisa de PEATE/BERA e, se necessário, intervenção especializada', NULL),
                (10, 0, 0, 1, 3, 'Na presente data apresentou respostas ausentes/insatisfatórias no teste e reteste “da orelhinha” (TAN) bilateralmente, com presença de indicadores de risco para deficiência auditiva (IRDA).', 'Foi realizada orientação verbal e entregue orientação escrita sobre a necessidade de avaliação para diagnóstico audiológico diferencial o mais breve possível, incluindo pesquisa de PEATE/BERA e, se necessário, intervenção especializada', NULL),
                (11, 1, 0, 1, 2, 'Na presente data apresentou respostas ausentes/insatisfatórias no reteste “da orelhinha” (TAN) à direita, com presença de indicadores de risco para deficiência auditiva (IRDA).', 'Foi realizada orientação verbal e entregue orientação escrita sobre a necessidade de avaliação para diagnóstico audiológico diferencial o mais breve possível, incluindo pesquisa de PEATE/BERA e, se necessário, intervenção especializada', NULL),
                (12, 0, 1, 1, 2, 'Na presente data apresentou respostas ausentes/insatisfatórias no reteste “da orelhinha” (TAN) à esquerda, com presença de indicadores de risco para deficiência auditiva (IRDA).', 'Foi realizada orientação verbal e entregue orientação escrita sobre a necessidade de avaliação para diagnóstico audiológico diferencial o mais breve possível, incluindo pesquisa de PEATE/BERA e, se necessário, intervenção especializada', NULL),
                (13, 1, 1, 0, 1, 'Na presente data apresentou respostas presentes/satisfatórias no “teste da orelhinha” (TAN), bilateralmente, sem presença de indicadores de risco para deficiência auditiva (IRDA).', 'Foi realizada orientação verbal e entregue orientação escrita sobre as etapas do desenvolvimento auditivo e de linguagem', NULL),
                (14, 1, 1, 1, 1, 'Na presente data apresentou respostas presentes/satisfatórias no “teste da orelhinha” (TAN), bilateralmente, com presença de indicadores de risco para deficiência auditiva (IRDA).', 'Como apresenta IRDA, necessita realizar PEATE-A no primeiro mês de vida e acompanhar o desenvolvimento auditivo nas consultas até os dois anos de idade. Por recomendações do Ministério da Saúde (2012), deverá realizar avaliação audiológica comportamental (VRA e imitância acústica) entre sete e 12 meses de idade. Foi realizada orientação verbal e entregue orientação escrita sobre as etapas do desenvolvimento auditivo e de linguagem', NULL),
                (15, 0, 0, 0, 1, 'Na presente data apresentou respostas ausentes/insatisfatórias no “teste da orelhinha” (TAN) bilateralmente, sem presença de indicadores de risco para deficiência auditiva (IRDA).', 'É obrigatória a realização de reteste dentro do primeiro mês de vida do bebê, idealmente 15 dias após o primeiro teste', NULL),
                (16, 1, 0, 0, 1, 'Na presente data apresentou respostas ausentes/insatisfatórias no “teste da orelhinha” (TAN) à direita, sem presença de indicadores de risco para deficiência auditiva (IRDA).', 'É obrigatória a realização de reteste dentro do primeiro mês de vida do bebê, idealmente 15 dias após o primeiro teste', NULL),
                (17, 0, 1, 0, 1, 'Na presente data apresentou respostas ausentes/insatisfatórias no “teste da orelhinha” (TAN) à esquerda, sem presença de indicadores de risco para deficiência auditiva (IRDA).', 'É obrigatória a realização de reteste dentro do primeiro mês de vida do bebê, idealmente 15 dias após o primeiro teste', NULL),
                (18, 0, 0, 1, 1, 'Na presente data apresentou respostas ausentes/insatisfatórias no “teste da orelhinha” (TAN) bilateralmente, com presença de indicadores de risco para deficiência auditiva (IRDA).', 'É obrigatória a realização de reteste dentro do primeiro mês de vida do bebê, idealmente 15 dias após o primeiro teste', NULL),
                (19, 1, 0, 1, 1, 'Na presente data apresentou respostas ausentes/insatisfatórias no “teste da orelhinha” (TAN) à direita, com presença de indicadores de risco para deficiência auditiva (IRDA).', 'É obrigatória a realização de reteste dentro do primeiro mês de vida do bebê, idealmente 15 dias após o primeiro teste', NULL),
                (20, 0, 1, 1, 1, 'Na presente data apresentou respostas ausentes/insatisfatórias no “teste da orelhinha” (TAN) à esquerda, com presença de indicadores de risco para deficiência auditiva (IRDA).', 'É obrigatória a realização de reteste dentro do primeiro mês de vida do bebê, idealmente 15 dias após o primeiro teste', NULL);
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        queryRunner.clearTable('conduta');
    }

}
